<?php
declare(strict_types=1);

namespace MonkeysLegion\Inertia\Ssr;

/**
 * MonKeysLegion Framework — Inertia Package
 *
 * Reads the Vite SSR manifest to resolve CSS/JS chunk URLs.
 *
 * The manifest is generated by Vite when running `vite build --ssr`.
 * It maps entry points to their built assets.
 *
 * @copyright 2026 MonkeysCloud Team
 * @license   MIT
 */
final class SsrManifest
{
    /** @var array<string, mixed> */
    private array $manifest;

    public function __construct(
        private readonly string $manifestPath,
    ) {
        $content = file_exists($manifestPath) ? file_get_contents($manifestPath) : '{}';
        $this->manifest = json_decode($content, true) ?? [];
    }

    /**
     * Get the JS file for a given entry.
     */
    public function getJsFile(string $entry): ?string
    {
        return $this->manifest[$entry]['file'] ?? null;
    }

    /**
     * Get the CSS files for a given entry.
     *
     * @return list<string>
     */
    public function getCssFiles(string $entry): array
    {
        return $this->manifest[$entry]['css'] ?? [];
    }

    /**
     * Get the imports (preload) for a given entry.
     *
     * @return list<string>
     */
    public function getImports(string $entry): array
    {
        return $this->manifest[$entry]['imports'] ?? [];
    }

    /**
     * Check if the manifest is loaded.
     */
    public function exists(): bool
    {
        return !empty($this->manifest);
    }

    /**
     * Get the raw manifest data.
     *
     * @return array<string, mixed>
     */
    public function all(): array
    {
        return $this->manifest;
    }
}
